[package]
name = "ororos_rs"
version = "0.1.0"

[dependencies]
heapless = "0.7.8"

[lib]
crate-type = ["staticlib"]

[profile.dev]
opt-level = 0
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
panic = 'abort'
